### ISSUE TITLE
Создать боковое меню и страницы в админ панели

### ISSUE THREAD

**Issue by shamilfrontend** [shamilfrontend/dentist-stalsk-crm#4]
@ruslanfrontend Создай плиз пункты в боковом меню

- Панель управления -> admin/index.vue
- Расписание -> admin/schedule/index.vue 
- Клиенты -> admin/clients/index.vue
- Сотрудники -> admin/employees/index.vue
- Финансы -> admin/finance/index.vue
- Настройки -> admin/settings/index.vue

А также эти странице в Админ панели, чтоб через меню можно было переходить по ним

**Comment by shamilfrontend** [comment]
Ветку можешь назвать feature/create-admin-pages

**Comment by ruslanfrontend** [comment]
done
